#!/usr/bin/env bash
# compile-gpugemv-shader.sh — AOT-compile Q4_K GEMV shaders to C headers.
#
# Compiles:
#   shaders/gpugemv_q4k.hlsl        → gpugemv_q4k_dxil.h        (naive, H6.1)
#   shaders/gpugemv_q4k_wave32.hlsl → gpugemv_q4k_wave32_dxil.h (H6.2 LDS-red)
#   shaders/gpugemv_q4k_rows.hlsl   → gpugemv_q4k_rows_dxil.h   (H6.3 multi-row)
#   shaders/gpugemv_q4k_dot4.hlsl   → gpugemv_q4k_dot4_dxil.h   (H6.3 int8 dot, cs_6_4)
#   shaders/ggml_d3d12_mmv_{q4_0,q4_k,q5_k,q6_k}.hlsl → ggml_d3d12_mmv_*_t{64,128}_dxil.h
#     (D2 backend; one blob per thread-group width, -D NUM_THREADS)
#
# Usage: compile-gpugemv-shader.sh [naive|wave32|rows|dot4|mmv_q4_0|mmv_q4_k|mmv_q5_k|mmv_q6_k ...]
#        (default: all)
# A different dxc release emits different bytes: regenerate only the targets
# you changed so measured blobs stay the ones the CSVs were recorded with.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DXC="${DXC:-dxc}"

if [[ ! -x "$DXC" ]] && ! command -v "$DXC" >/dev/null 2>&1; then
	echo "dxc not found (set DXC=...). Example Linux release:" >&2
	echo "  https://github.com/microsoft/DirectXShaderCompiler/releases" >&2
	echo "  pacman extra/directx-shader-compiler (do not install AUR packages)" >&2
	exit 1
fi

emit_header() {
	local dxil="$1"
	local out_h="$2"
	local source_rel="$3"
	local symbol="$4"
	local profile="$5"
	python3 - "$dxil" "$out_h" "$source_rel" "$symbol" "$profile" <<'PY'
import sys
from pathlib import Path

data = Path(sys.argv[1]).read_bytes()
out = Path(sys.argv[2])
source = sys.argv[3]
symbol = sys.argv[4]
profile = sys.argv[5]
out.parent.mkdir(parents=True, exist_ok=True)
lines = [
    "// AUTO-GENERATED by scripts/compile-gpugemv-shader.sh — do not edit.",
    f"// Source: {source} ({profile} CSMain)",
    "#pragma once",
    "#include <cstddef>",
    "#include <cstdint>",
    f"// {len(data)} bytes DXIL",
    "// clang-format off",
    f"static const uint8_t {symbol}[] = {{",
]
for i in range(0, len(data), 12):
    chunk = data[i : i + 12]
    lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
lines.append("};")
lines.append(f"static const size_t {symbol}Size = {len(data)};")
lines.append("// clang-format on")
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({len(data)} bytes)")
PY
}

compile_one() {
	local hlsl="$1"
	local out_h="$2"
	local source_rel="$3"
	local symbol="$4"
	local profile="$5"
	shift 5
	local tmp
	tmp="$(mktemp)"
	"$DXC" -T "$profile" -E CSMain "$@" -Fo "$tmp" "$hlsl"
	emit_header "$tmp" "$out_h" "$source_rel" "$symbol" "$profile"
	rm -f "$tmp"
}

compile_target() {
	case "$1" in
	naive) compile_one "$ROOT/shaders/gpugemv_q4k.hlsl" \
		"$ROOT/shaders/generated/gpugemv_q4k_dxil.h" \
		"shaders/gpugemv_q4k.hlsl" "kGpugemvQ4kDxil" cs_6_0 ;;
	wave32) compile_one "$ROOT/shaders/gpugemv_q4k_wave32.hlsl" \
		"$ROOT/shaders/generated/gpugemv_q4k_wave32_dxil.h" \
		"shaders/gpugemv_q4k_wave32.hlsl" "kGpugemvQ4kWave32Dxil" cs_6_0 ;;
	rows) compile_one "$ROOT/shaders/gpugemv_q4k_rows.hlsl" \
		"$ROOT/shaders/generated/gpugemv_q4k_rows_dxil.h" \
		"shaders/gpugemv_q4k_rows.hlsl" "kGpugemvQ4kRowsDxil" cs_6_0 ;;
	dot4) compile_one "$ROOT/shaders/gpugemv_q4k_dot4.hlsl" \
		"$ROOT/shaders/generated/gpugemv_q4k_dot4_dxil.h" \
		"shaders/gpugemv_q4k_dot4.hlsl" "kGpugemvQ4kDot4Dxil" cs_6_4 ;;
	mmv_q4_0 | mmv_q4_k | mmv_q5_k | mmv_q6_k)
		local t="${1#mmv_}" w sym
		for w in 64 128; do
			sym="kGgmlD3d12Mmv$(echo "$t" | sed -e 's/_\(.\)/\U\1/g' -e 's/^./\U&/')T${w}Dxil"
			compile_one "$ROOT/shaders/ggml_d3d12_mmv_${t}.hlsl" \
				"$ROOT/shaders/generated/ggml_d3d12_mmv_${t}_t${w}_dxil.h" \
				"shaders/ggml_d3d12_mmv_${t}.hlsl -D NUM_THREADS=${w}" "$sym" cs_6_0 \
				-D "NUM_THREADS=${w}"
		done
		;;
	*)
		echo "unknown target: $1 (naive|wave32|rows|dot4|mmv_q4_0|mmv_q4_k|mmv_q5_k|mmv_q6_k)" >&2
		exit 2
		;;
	esac
}

if [[ $# -eq 0 ]]; then
	set -- naive wave32 rows dot4 mmv_q4_0 mmv_q4_k mmv_q5_k mmv_q6_k
fi
for target in "$@"; do
	compile_target "$target"
done
